// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'Linux is not supported by this app.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9iXr9nqNsJRInJ-dEj0EKy2SzmnMZLg',
    appId: '1:396184200838:web:98a5a9ffd18da28f39d307',
    messagingSenderId: '396184200838',
    projectId: 'omniotp-84dba',
    authDomain: 'omniotp-84dba.firebaseapp.com',
    storageBucket: 'omniotp-84dba.firebasestorage.app',
    measurementId: 'G-B7Z9PR7ZR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPLwvzSYyQQISVRJrDAC9WEV53m610WA',
    appId: '1:396184200838:android:c373ceb3d6b31b6c39d307',
    messagingSenderId: '396184200838',
    projectId: 'omniotp-84dba',
    storageBucket: 'omniotp-84dba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZXsIUx9k8JGRcB8htBEkzARfIL5Pnd-8',
    appId: '1:396184200838:ios:c03b36e15c41c8a939d307',
    messagingSenderId: '396184200838',
    projectId: 'omniotp-84dba',
    storageBucket: 'omniotp-84dba.firebasestorage.app',
    iosBundleId: 'com.example.omniotp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZXsIUx9k8JGRcB8htBEkzARfIL5Pnd-8',
    appId: '1:396184200838:ios:c03b36e15c41c8a939d307',
    messagingSenderId: '396184200838',
    projectId: 'omniotp-84dba',
    storageBucket: 'omniotp-84dba.firebasestorage.app',
    iosBundleId: 'com.example.omniotp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9iXr9nqNsJRInJ-dEj0EKy2SzmnMZLg',
    appId: '1:396184200838:web:4ece118d95876e3439d307',
    messagingSenderId: '396184200838',
    projectId: 'omniotp-84dba',
    authDomain: 'omniotp-84dba.firebaseapp.com',
    storageBucket: 'omniotp-84dba.firebasestorage.app',
    measurementId: 'G-NML8ES7N74',
  );
}
